package pss.trabalho.view;

import javax.swing.*;

/**
 *
 * @author Marcelo Augusto
 */
public class MainView extends javax.swing.JFrame {

    public MainView() {
        initComponents();
    }

    public JDesktopPane getjDesktop() {
        return jDesktop;
    }

    public JLabel getTxtTipo() {
        return txtTipo;
    }

    public JLabel getTxtUsuario() {
        return txtUsuario;
    }

    public JButton getBtnNotificacao() {
        return btnNotificacao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jDesktop = new javax.swing.JDesktopPane();
        jpanel = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JLabel();
        txtTipo = new javax.swing.JLabel();
        btnNotificacao = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        menuOpDefinirLog = new javax.swing.JMenuItem();
        menuOpSair = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        txtUsuario.setText("Usuario");

        txtTipo.setText("Tipo");

        btnNotificacao.setText("0");
        btnNotificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelLayout = new javax.swing.GroupLayout(jpanel);
        jpanel.setLayout(jpanelLayout);
        jpanelLayout.setHorizontalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLayout.createSequentialGroup()
                .addContainerGap(439, Short.MAX_VALUE)
                .addComponent(txtUsuario)
                .addGap(31, 31, 31)
                .addComponent(txtTipo)
                .addGap(21, 21, 21)
                .addComponent(btnNotificacao)
                .addContainerGap())
        );
        jpanelLayout.setVerticalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnNotificacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTipo)
                    .addComponent(txtUsuario))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        menu.setText("Opções");

        menuOpDefinirLog.setText("Definir Log");
        menu.add(menuOpDefinirLog);

        menuOpSair.setText("Sair");
        menu.add(menuOpSair);

        menuBar.add(menu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNotificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNotificacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNotificacao;
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jpanel;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuOpDefinirLog;
    private javax.swing.JMenuItem menuOpSair;
    private javax.swing.JLabel txtTipo;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables


    public JMenuItem getMenuOpDefinirLog() {
        return menuOpDefinirLog;
    }

    public JMenuItem getMenuOpSair() {
        return menuOpSair;
    }
}
