/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pss.trabalho.view;

import javax.swing.*;

/**
 *
 * @author joaovictor
 */
public class UserListView extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserList
     */
    public UserListView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        newUserBtn = new javax.swing.JButton();
        viewUserBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        searchTypeBox = new javax.swing.JComboBox<>();
        searchTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Data de cadastro", "Notificações enviadas", "Notificações lidas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userTable.setSelectionBackground(new java.awt.Color(102, 102, 255));
        userTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(userTable);

        newUserBtn.setBackground(new java.awt.Color(102, 102, 255));
        newUserBtn.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        newUserBtn.setForeground(new java.awt.Color(255, 255, 255));
        newUserBtn.setText("Novo");
        newUserBtn.setBorderPainted(false);

        viewUserBtn.setBackground(new java.awt.Color(102, 102, 255));
        viewUserBtn.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        viewUserBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewUserBtn.setText("Visualizar");
        viewUserBtn.setBorderPainted(false);

        closeBtn.setBackground(new java.awt.Color(102, 102, 255));
        closeBtn.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        closeBtn.setForeground(new java.awt.Color(255, 255, 255));
        closeBtn.setText("Fechar");
        closeBtn.setBorderPainted(false);

        searchTypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome" }));

        searchBtn.setBackground(new java.awt.Color(102, 102, 255));
        searchBtn.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Buscar");
        searchBtn.setBorderPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(newUserBtn)
                                .addGap(18, 18, 18)
                                .addComponent(viewUserBtn)
                                .addGap(18, 18, 18)
                                .addComponent(closeBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchBtn)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newUserBtn)
                    .addComponent(viewUserBtn)
                    .addComponent(closeBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newUserBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JComboBox<String> searchTypeBox;
    private javax.swing.JTable userTable;
    private javax.swing.JButton viewUserBtn;
    // End of variables declaration//GEN-END:variables


    public JButton getCloseBtn() {
        return closeBtn;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JButton getNewUserBtn() {
        return newUserBtn;
    }

    public JButton getSearchBtn() {
        return searchBtn;
    }

    public JTextField getSearchTxt() {
        return searchTxt;
    }

    public JComboBox<String> getSearchTypeBox() {
        return searchTypeBox;
    }

    public JTable getUserTable() {
        return userTable;
    }

    public JButton getViewUserBtn() {
        return viewUserBtn;
    }
}
